version: '3.11'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: smart_advisor
      POSTGRES_USER: smart_advisor
      POSTGRES_PASSWORD: smart_advisor
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    image: mahibrahim/smart-advisor-backend:1.0.0
    environment:
      DATABASE_URL: postgresql+asyncpg://smart_advisor:smart_advisor@db:5432/smart_advisor
      ALPHAVANTAGE_API_KEY: W7NAEL9D8ERL47FW
      TELEMETRY_ENABLED: "true"
      TELEMETRY_SERVICE_NAME: smart-advisor
      OTEL_SERVICE_NAME: smart-advisor-backend
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev,service.version=1.0.0
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
      OTEL_LOGS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_LOGS_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://1otel-collector:4318/v1/logs
      OTEL_METRICS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
    depends_on:
      - db
    ports:
      - '8000:8000'

  frontend:
    build:
      context: ./frontend
    image: mahibrahim/smart-advisor-frontend:1.0.0
    depends_on:
      - backend
    ports:
      - '4200:80'

volumes:
  db_data:
